### ISSUE TITLE
Can't connect 

### ISSUE THREAD

**Issue by vatato** [vhar/withrottle#2]
Hello 
Engine driver or winthrottle  can't connect to the server (10.10.10.10:44444)
WiFi works, signal is good

**Comment by vhar** [comment]
> Invalid library found in /Users/vatato/Documents/Arduino/libraries/withrottle-master: no headers files (.h) found in /Users/vatato/Documents/Arduino/libraries/withrottle-master

Judging by your logs, you saved a sketch to the libraries folder. Sketches are only allowed in that folder as examples inside the folder of a valid library. Fix: move the sketch anywhere else other than the libraries folder.
